name: Report a bug
description: Report a bug to help improve RESIC.
labels: ["bug"]
assignees:
  - LibertyNJ
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report!

        Please enter a short, descriptive title above.

        If you are reporting a security vulnerability, please do not complete this bug
        report. See the [security policy](https://github.com/LibertyNJ/resic?tab=security-ov-file#readme) instead.

        If RESIC prompted you to include any details, please be sure to include them below.
  - type: input
    id: resic-version
    attributes:
      label: RESIC Version
      description: Which version of RESIC are you using?
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: Rust Compiler Version
      description: Which version of Rust are you using?
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the scenario and provide as many details as possible.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copy and paste any relevant log output.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this bug report, you agree to follow our
        [Code of Conduct](https://github.com/LibertyNJ/resic?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
